### ISSUE TITLE
Acabar el juego

### ISSUE THREAD

**Issue by nasivuela** [Adalab/dorcas-s2-evaluacion-intermedia-Sinsit1#1]
Ole Alex! Tu ejercicio tiene muy buena pinta! te dejo algunas sugerencias con cositas a mejorar:

- Hay que darle cariño a la indentación del HTML
- Podriamos acceder a los elementos del DOM **una sola** vez y asignarlos a variables. Así en el callback del click solo tendriamos que acceder a la propiedad que nos devuelve su valor ;)
- Al asignar el valor del input a una variable podemos hacerlo ya parseado como número, y así nos ahorramos un segundo paso => `var inputNumber = parseInt(input.value)`
- BONUS extra: ¿Que pasaría si la usuaria pone un valor no númerico en el input? ¿Y si fuera uno númerico mayor que 100 o menor que 1?

A por ello!

**Comment by Sinsit1** [comment]
Buenas!
Ya le he dado cariñito al HTML... tengo que integrar más eso en mi cabeza cuando voy con prisas...

> Podriamos acceder a los elementos del DOM una sola vez y asignarlos a variables. Así en el callback del click solo tendriamos que acceder a la propiedad que nos devuelve su valor
> valor ;)
No entiendo esta parte...¿?

Bonus extra DONE. Ya está controlado que se meta un valor no numérico, y un valor por encima de 100 y por debajo de 0.

**Comment by nasivuela** [comment]
Quiero decir que cada vez que la usuaria hace click tú estás accediendo a unos elementos del DOM con `querySelector`. Estos elementos siempre son los mismos, no hace falta acceder a ellos en cada click, podríamos mover los `querySelector` fuera del callback sin problema y así ahorramos en accesos al DOM!

**Comment by nasivuela** [comment]
Solo es un detallico, pero tu ejercicio esta muy chachi!!!

Yeaaahh!

![](https://media.giphy.com/media/WsKVAem02Efuw/giphy.gif)
